[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "meta-agent"
dynamic = ["version"]
description = 'init hatch'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Danny McAteer", email = "mcateerd2@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "openai-agents~=0.0.11",
    "pytest",
    "ruff",
    "pydantic>=2",  # Added for data validation models
    "pyyaml>=6",    # Added for potential YAML parsing
    "click>=8",     # Added for CLI implementation
]

[project.urls]
Documentation = "https://github.com/Danny McAteer/meta-agent#readme"
Issues = "https://github.com/Danny McAteer/meta-agent/issues"
Source = "https://github.com/Danny McAteer/meta-agent"

[project.scripts]
meta-agent = "meta_agent.cli.main:cli"

[tool.hatch.version]
path = "src/meta_agent/__about__.py"

[tool.hatch.envs.default]
[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"

[tool.hatch.envs.test]
dependencies = [
  "pytest",
  "pytest-cov", # Added for coverage
]
[tool.hatch.envs.test.scripts]
test = "pytest {args:tests}" # Script to run pytest
cov = "pytest --cov=src/meta_agent --cov-report=term-missing {args:tests}" # Script for coverage

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/meta_agent tests}"

[tool.coverage.run]
source_pkgs = ["meta_agent", "tests"]
branch = true
parallel = true
omit = [
  "src/meta_agent/__about__.py",
]

[tool.coverage.paths]
meta_agent = ["src/meta_agent", "*/meta-agent/src/meta_agent"]
tests = ["tests", "*/meta-agent/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
[tool.hatch.scripts]
test = { env = "test", run = "pytest {args:tests}" }
[tool.hatch.build.targets.wheel]
packages = ["src/meta_agent"]
