[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "danmac-meta-agent"
version = "0.1.0"
description = "A meta agent that creates OpenAI Agents SDK agents"
readme = "README.md"
authors = [
    {name = "Meta Agent Developer"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.8"
dependencies = [
    "openai-agents @ git+https://github.com/openai/openai-agents-python.git@v0.0.5",
    "pydantic",
    "asyncio",
    "typing",
    "python-dotenv",
    "requests",
    "beautifulsoup4",
]

[project.urls]
"Homepage" = "https://github.com/DannyMac180/meta-agent"
"Bug Tracker" = "https://github.com/DannyMac180/meta-agent/issues"
"Documentation" = "https://github.com/DannyMac180/meta-agent#readme"
"Source Code" = "https://github.com/DannyMac180/meta-agent"

[project.scripts]
danmac-meta-agent = "meta_agent.cli:main"

[tool.setuptools]
packages = ["meta_agent"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "--strict-markers -v"
markers = [
    "unit: mark a test as a unit test",
    "integration: mark a test as an integration test",
    "slow: mark test as slow (longer than 1s)",
    "api: tests that require API access",
    "asyncio: mark test as an asyncio test"
]
