[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "meta-agent"
dynamic = ["version"]
requires-python = ">=3.11"      # match the image default 3.11.12 :contentReference[oaicite:1]{index=1}
dependencies = [
  # -- runtime only --
  "openai-agents~=0.0.11",
  "pydantic>=2",
  "pyyaml>=6",
  "click>=8",
  "docker>=7",
  "Jinja2>=3.0.0",
  "python-dotenv>=1.0.0",
  "aiohttp~=3.9",
  "backoff>=2.2.1,<3.0.0",
]

[project.scripts]
meta-agent = "meta_agent.cli.main:cli"

[tool.hatch.version]
path = "src/meta_agent/__about__.py"

# ➜ A *system* env that re-uses the already-installed interpreter
[tool.hatch.envs.default]
python = "sys"            # ← critical: don’t create a new venv
dependencies = []         # rely on the setup script’s pip install

# ➜ Testing env piggy-backs on the same interpreter
[tool.hatch.envs.test]
python = "sys"
dependencies = [
  "pytest-cov",
  "pytest-mock",
]
[tool.hatch.envs.test.scripts]
run = "pytest {args:tests}"
cov = "pytest --cov=src/meta_agent --cov-branch {args:tests}"

# Static type env – mypy is preinstalled in the image :contentReference[oaicite:2]{index=2}
[tool.hatch.envs.types]
python = "sys"
extra-dependencies = []
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/meta_agent tests}"
