version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: metaagent-postgres
    environment:
      POSTGRES_DB: metaagent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d metaagent"]
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:7-alpine
    container_name: metaagent-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
  minio:
    image: minio/minio:latest
    container_name: metaagent-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
volumes:
  pgdata:
  minio-data:
