name: pytest

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --extra test
      - name: Run test suite
        env:
          # Ensure OpenAI API key is not required for tests (they should be mocked)
          OPENAI_API_KEY: "test-key-for-ci"
        run: |
          uv run pytest -v --cov=src/meta_agent tests
